### ISSUE TITLE
Missing something to work as expected in 1.16.2

### ISSUE THREAD

**Issue by d-faure** [supersmartypants/BoostedBrightness#2]
Once clicked on the graphic options:
```
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:440) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:92) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:162) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:162) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:308) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1043) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:656) [intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.2-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.2+build.206.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoSuchMethodError: net.minecraft.class_4067.method_18518()Lnet/minecraft/class_5250;
	at net.minecraft.class_4067.md482591$lambda$init$0$0(class_4067.java:540) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_4067.method_18619(class_4067.java:73) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_4040.method_25346(class_4040.java:27) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_4040.<init>(class_4040.java:16) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_4067.method_18520(class_4067.java:33) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_353$class_354.method_20410(class_353.java:79) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_353.method_20407(class_353.java:25) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_353.method_20408(class_353.java:30) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_446.method_25426(class_446.java:67) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:325) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:897) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_429.method_19828(class_429.java:85) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:33) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:16) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:149) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:92) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:435) ~[intermediary-minecraft-1.16.2-client.jar:?]
```

**Comment by Bstn1802** [comment]
i fixed that error and made a pull request
